package: add the vite plugin
Fixes the following error

```
vite v1.0.0-rc.4
[vite] failed to load config from /workspace/5-minute-journal/vite.config.js:
Error: Cannot find module 'vite-plugin-imba'
Require stack:
- /workspace/5-minute-journal/vite.config.js
- /workspace/5-minute-journal/node_modules/vite/dist/node/config.js
- /workspace/5-minute-journal/node_modules/vite/dist/node/cli.js
- /workspace/5-minute-journal/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/workspace/5-minute-journal/vite.config.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .js] (/workspace/5-minute-journal/node_modules/vite/dist/node/config.js:108:20)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/5-minute-journal/vite.config.js',
    '/workspace/5-minute-journal/node_modules/vite/dist/node/config.js',
    '/workspace/5-minute-journal/node_modules/vite/dist/node/cli.js',
    '/workspace/5-minute-journal/node_modules/vite/bin/vite.js'
  ]
}
```